import { RouterProvider, createBrowserRouter } from "react-router-dom";
import MainLayout from "./components/MainLayout";
import Home from "./pages/Home";
import About from "./pages/About";
import Gallery from "./pages/Gallery";
import ItemDetail from "./pages/ItemDetail";
import Contact from "./pages/Contact";

const router = createBrowserRouter([
  {
    path: "/",
    element: <MainLayout />,
    children: [
      {
        path: "/",
        element: <Home />,
      },
      {
        path: "/about",
        element: (
          <About
            title="About the AI Gallery"
            description="showcases a diverse range of artwork generated by artificial intelligence. Our collection includes unique and creative pieces that push the boundaries of traditional art."
          />
        ),
      },
      {
        path: "/gallery",
        element: <Gallery />,
      },
      {
        path: "/item/:id",
        element: <ItemDetail />,
      },
      {
        path: "/contact",
        element: <Contact />,
      },
    ],
  },
]);

function App() {
  return <RouterProvider router={router} />;
}

export default App;
